name: Android CI

on:
  push:
    branches:
      - main
      - nasrin-report-incident
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK 11 (required for Android Gradle plugin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          target-sdk: 34
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true

      # Verify Gradle Wrapper
      - name: Verify Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 8.1 --distribution-type all

      # Build the project
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Run instrumentation tests
      - name: Run Instrumentation Tests
        run: ./gradlew connectedAndroidTest

      # Archive build outputs (optional)
      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
